---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO:-ubuntu/focal64}
    memory: 2048
    cpus: 2
    # Dictionary of `config` options.
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: "'vagrant'"
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
  inventory:
    group_vars:
      all:
        ansible_user: admin
        local_group: ${HOST_GROUP:-nogroup}
        admin_accounts:
          - username: admin2
          - username: admin3
        user_accounts:
          - username: user2
          - username: user3
        base_domain: "{{ inventory_hostname }}"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
